name: build

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "kovrichard/chat"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      
      - name: Lint project
        run: bun run lint-check && bun run type-check

      - name: Migrate database
        run: bun run db-push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  build:
    needs: test
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: latest
            authority: ""
          - tag: hosted
            authority: "www.fyzz.chat"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push ${{ matrix.tag }} image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: release
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          build-args: |
            AUTHORITY=${{ matrix.authority }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Coolify
        run: | 
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
